export * from './authorization.module';
export * from './domain/owned-resource';
export * from './domain/owner-scope';
export * from './domain/repositories/family-membership.repository.interface';
export * from './domain/repositories/resource-owner.repository.interface';
export * from './application/use-cases/resolve-owner-scope.use-case';
export * from './application/use-cases/verify-resource-access.use-case';
export * from './rest/decorators/owns-resource.decorator';
export * from './rest/guards/resource-ownership.guard';
