export const RECEIPT_MAX_FILE_SIZE = 100 * 1024 * 1024; // 100MB
export const RECEIPT_ALLOWED_MIME_TYPES = ['image/jpeg', 'image/png'];
export const RECEIPT_LOW_CONFIDENCE_THRESHOLD = 50;
export const RECEIPT_CAPTURE_IDEAL_WIDTH = 4096;
export const RECEIPT_CAPTURE_IDEAL_HEIGHT = 4096;
export const RECEIPT_JPEG_QUALITY = 1;
